### ISSUE TITLE
Todo 2/10

### ISSUE THREAD

**Issue by coryp** [SilversphereInc/AccelerateVIP-iOS#1]
- [x] **homescreen icon**
- [x] **change top X to back arrow**

Schedule
- [ ] change date labels?
- [ ] reformat event times

Guest list
- [ ] add some padding between rows
- [ ] turn off row select color

Track facts
- [ ] create page
- [x] **direct to new page (http://www.acceleratevip.com/trackfacts)**

Photos
- [ ] compression on upload
- [ ] rotation?
- [ ] better "take photo" button

Push
- [ ] pay for Parse

Deployment
- [ ] **test production push notification**
- [x] **prepare for submission**
